# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - package.json
    - package-lock.json
    - buildspec.yml
    - .platform/**/*
    - service-account-file.json
    - src/**/*
    - node_modules/**/*
